// Mocks generated by Mockito 5.4.4 from annotations
// in ToDo/test/src/app/logic/task/create_update/bloc/task_create_update_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ToDo/src/domain/models/task/task_item.dart' as _i2;
import 'package:ToDo/src/domain/usecase/task/createupdate/task_create_update_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskItem_0 extends _i1.SmartFake implements _i2.TaskItem {
  _FakeTaskItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskCreateUpdateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskCreateUpdateUseCase extends _i1.Mock
    implements _i3.TaskCreateUpdateUseCase {
  MockTaskCreateUpdateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TaskItem> invoke(_i2.TaskItem? taskItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [taskItem],
        ),
        returnValue: _i4.Future<_i2.TaskItem>.value(_FakeTaskItem_0(
          this,
          Invocation.method(
            #invoke,
            [taskItem],
          ),
        )),
      ) as _i4.Future<_i2.TaskItem>);
}
