name: ToDo
description: Todo Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  sqflite: ^2.3.0
  animations: ^2.0.8
  shamsi_date: ^1.0.2
  scroll_to_index: ^3.0.1
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.2.0
  bloc_test: ^9.1.5
  sqflite_common_ffi: ^2.3.0+2
  test: ^1.24.3
  faker: ^2.1.0


flutter:
  assets:
    - assets/images/
    - assets/lottie/
    - i18n/en.json
    - i18n/fa.json

  fonts:
    - family: Iran
      fonts:
        - asset: assets/fonts/iran.ttf
        - asset: assets/fonts/iran_b.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
        - asset: assets/fonts/raleway_b.ttf
          weight: 700


  uses-material-design: true